backend:
  name: github
  repo: urayasu-portal/urayasu-portal
  branch: main

media_folder: static/images/uploads
public_folder: /images/uploads

locale: ja

collections:
  - name: posts
    label: 記事
    folder: content/posts
    create: true
    slug: "{{slug}}"
    fields:
      - label: タイトル
        name: title
        widget: string
      - label: 公開日
        name: date
        widget: datetime
        format: "YYYY-MM-DDTHH:mm:ssZ"
        date_format: "YYYY-MM-DD"
        time_format: "HH:mm"
      - label: カテゴリ
        name: categories
        widget: select
        multiple: true
        options:
          - { label: "開店・閉店", value: "開店・閉店" }
          - { label: "ニュース", value: "ニュース" }
          - { label: "イベント", value: "イベント" }
          - { label: "グルメ・カフェ", value: "グルメ・カフェ" }
          - { label: "子育て・教育", value: "子育て・教育" }
          - { label: "スポーツ", value: "スポーツ" }
          - { label: "お知らせ", value: "お知らせ" }
      - label: アイキャッチ画像
        name: cover
        widget: object
        required: false
        fields:
          - label: 画像URL
            name: image
            widget: image
            required: false
          - label: 代替テキスト
            name: alt
            widget: string
            required: false
      - label: 本文
        name: body
        widget: markdown
